"""Deterministic PT-BR composition of the `t_roadsigns` atlas (Phase 5 master).

Starts from the ORIGINAL game PNGs (source/originals/png, SHA-256 checked against the
manifest), edits only the elements listed in layout.json, and writes:

    working/png/t_roadsigns_b.color.png   (base colour)
    working/png/t_roadsigns_o.data.png    (opacity: only glyph tiles change)

    python working/layered/t_roadsigns/build_t_roadsigns.py regions   # UV evidence -> regions.json + allowed_regions.json
    python working/layered/t_roadsigns/build_t_roadsigns.py build     # compose the PNGs
    python working/layered/t_roadsigns/build_t_roadsigns.py preview   # crops before/after in working/temporary

Nothing is generated by AI; everything is text rendered with a system font over the
original pixels, and every pixel outside the element boxes is copied untouched.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
sys.path.insert(0, str(REPO / "tools/production"))
sys.path.insert(0, str(REPO / "tools/validation"))

ORIG_COLOR = REPO / "source/originals/png/t_roadsigns_b.color.png"
ORIG_OPACITY = REPO / "source/originals/png/t_roadsigns_o.data.png"
OUT_COLOR = REPO / "working/png/t_roadsigns_b.color.png"
OUT_OPACITY = REPO / "working/png/t_roadsigns_o.data.png"
LAYOUT = HERE / "layout.json"
REGIONS = HERE / "regions.json"
MESH_USAGE = HERE / "mesh_usage.json"
MESH_DIR = REPO / "source/originals/meshes"
ALLOWED = REPO / "tools/validation/config/allowed_regions.json"
FONTS = {"bahnschrift": "C:/Windows/Fonts/bahnschrift.ttf"}
SS = 4  # text supersampling
LEGEND = {
    "white": lambda a: (a[..., 0] > 175) & (a[..., 1] > 175) & (a[..., 2] > 175),
    "red": lambda a: (a[..., 0] > 120) & (a[..., 0] > a[..., 1] + 50) & (a[..., 0] > a[..., 2] + 50),
    "black": lambda a: (a.max(-1) < 110),
    "green": lambda a: (a[..., 1] > a[..., 0] + 20) & (a[..., 1] > 60) & (a[..., 0] < 150),
}


# ---------------------------------------------------------------- inputs
def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def manifest_sha(name: str) -> str:
    import csv
    with open(REPO / "docs/inventory/original_files_manifest.csv", encoding="utf8") as f:
        for row in csv.DictReader(f):
            if row["filename"] == name and row["classification"].startswith("original"):
                return row["sha256"]
    raise SystemExit(f"{name} not in manifest")


def load_originals():
    for p in (ORIG_COLOR, ORIG_OPACITY):
        if not p.exists():
            raise SystemExit(f"missing original {p} (see docs/inventory/original_files_manifest.csv)")
        if sha256(p) != manifest_sha(p.name):
            raise SystemExit(f"SHA-256 mismatch for {p.name}: stop and investigate")
    color = np.array(Image.open(ORIG_COLOR).convert("RGBA"))
    opacity = np.array(Image.open(ORIG_OPACITY).convert("RGBA"))
    assert color.shape == (1024, 2048, 4) and opacity.shape == (1024, 2048, 4)
    return color, opacity


# ---------------------------------------------------------------- helpers
def box_slices(b):
    x0, y0, x1, y1 = b
    return slice(y0, y1), slice(x0, x1)


def dilate(m: np.ndarray, r: int) -> np.ndarray:
    out = m.copy()
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            if dy * dy + dx * dx <= r * r:
                out |= np.roll(np.roll(m, dy, 0), dx, 1)
    return out


def box_blur(img: np.ndarray, r: int) -> np.ndarray:
    k = 2 * r + 1
    pad = np.pad(img, ((r, r), (r, r)) + ((0, 0),) * (img.ndim - 2), mode="edge").astype(np.float64)
    c = pad.cumsum(0).cumsum(1)
    c = np.pad(c, ((1, 0), (1, 0)) + ((0, 0),) * (img.ndim - 2))
    s = c[k:, k:] - c[:-k, k:] - c[k:, :-k] + c[:-k, :-k]
    return s / (k * k)


def inpaint(rgb: np.ndarray, hole: np.ndarray, rng: np.random.Generator, iters: int = 400) -> np.ndarray:
    """Diffusion fill of `hole` from the surrounding pixels, then re-grain with residuals of known pixels."""
    out = rgb.astype(np.float64).copy()
    known = ~hole
    if not known.any():
        return rgb
    out[hole] = out[known].mean(0)
    for _ in range(iters):
        acc = np.zeros_like(out)
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            acc += np.roll(np.roll(out, dy, 0), dx, 1)
        out[hole] = (acc / 4.0)[hole]
    base = rgb.astype(np.float64)
    clean = known & ~dilate(hole, 3)
    resid = (base - box_blur(base, 2))[clean]
    if len(resid):
        resid = np.clip(resid, -10, 10) * 0.8
        pick = rng.integers(0, len(resid), hole.sum())
        out[hole] += resid[pick]
    return out.clip(0, 255)


def grain_color(src: np.ndarray, sel: np.ndarray, rng, n: int) -> np.ndarray:
    """n colours = median legend colour + residual grain sampled from `sel` pixels of src."""
    pix = src[sel].astype(np.float64)
    med = np.median(pix, 0)
    if len(pix) < 4:
        return np.tile(med, (n, 1))
    resid = pix - pix.mean(0)
    resid = np.clip(resid, -25, 25) * 0.6
    return med + resid[rng.integers(0, len(pix), n)]


def font(spec: dict, size: int) -> ImageFont.FreeTypeFont:
    f = ImageFont.truetype(FONTS[spec.get("font", "bahnschrift")], size)
    try:
        f.set_variation_by_axes([spec.get("wght", 600), spec.get("wdth", 100)])
    except OSError:
        pass
    return f


def render_line(text: str, spec: dict, box, cap_ref="H") -> np.ndarray:
    """Coverage of `text`: capital height == box height; narrows the font width axis (down to
    `min_wdth`) before squeezing horizontally, so long PT-BR words keep real letter shapes."""
    spec = dict(spec)
    wd = spec.get("wdth", 100)
    while True:
        cov, ink_w = _render_line(text, spec, box, cap_ref)
        if ink_w <= (box[2] - box[0]) * spec.get("max_width", 1.0) or spec["wdth"] <= spec.get("min_wdth", 75):
            spec["_final_wdth"] = spec["wdth"]
            return cov
        spec["wdth"] = max(spec.get("min_wdth", 75), spec["wdth"] - 5)


def _render_line(text: str, spec: dict, box, cap_ref="H"):
    spec.setdefault("wdth", 100)
    x0, y0, x1, y1 = box
    bw, bh = x1 - x0, y1 - y0
    probe = font(spec, 200)
    cb = probe.getbbox(cap_ref)
    cap = cb[3] - cb[1]
    size = max(4, int(round(200 * bh * SS / cap)))
    f = font(spec, size)
    smallcaps = spec.get("smallcaps", False)
    if smallcaps:
        f2 = font(spec, int(size * spec.get("smallcaps_ratio", 0.78)))
    tb = f.getbbox(cap_ref)
    top_off = tb[1]
    # measure
    parts = [(text[0], f), (text[1:], f2)] if smallcaps else [(text, f)]
    widths = [ff.getlength(t) for t, ff in parts]
    tracking = spec.get("tracking", 0) * SS
    total = sum(widths) + tracking * max(0, len(text) - 1)
    pad_top = int(bh * SS * 0.6)
    H = bh * SS + 2 * pad_top
    W = int(total) + 8 * SS
    canvas = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(canvas)
    x = 4 * SS
    baseline_y = pad_top - top_off  # glyph top of caps at pad_top
    for (t, ff), w in zip(parts, widths):
        if tracking:
            for ch in t:
                d.text((x, baseline_y + (tb[3] - ff.getbbox(cap_ref)[3] if ff is not f else 0)), ch, font=ff, fill=255)
                x += ff.getlength(ch) + tracking
        else:
            dy = (f.getbbox(cap_ref)[3] - ff.getbbox(cap_ref)[3]) if ff is not f else 0
            d.text((x, baseline_y + dy), t, font=ff, fill=255)
            x += w
    arr = np.array(canvas)
    cols = np.nonzero(arr.max(0) > 0)[0]
    arr = arr[:, cols.min():cols.max() + 1]
    ink_w = arr.shape[1]
    target_w = min(ink_w, bw * SS * spec.get("max_width", 1.0)) if not spec.get("stretch") else bw * SS
    sx = target_w / ink_w
    img = Image.fromarray(arr).resize((max(1, int(round(ink_w * sx / SS))), H // SS), Image.LANCZOS)
    cov = np.asarray(img, dtype=np.float64) / 255.0
    # place: cap top at y0; accents may rise above (pad_top/SS rows)
    full = np.zeros((1024, 2048))
    ph = pad_top // SS
    w = cov.shape[1]
    align = spec.get("align", "center")
    if align == "left":
        px = x0
    elif align == "right":
        px = x1 - w
    else:
        px = x0 + (bw - w) // 2
    py = y0 - ph
    ys0, xs0 = max(py, 0), max(px, 0)
    ys1, xs1 = min(py + cov.shape[0], 1024), min(px + w, 2048)
    full[ys0:ys1, xs0:xs1] = cov[ys0 - py:ys1 - py, xs0 - px:xs1 - px]
    return full, ink_w / SS


def connected(m: np.ndarray, sy: int, sx: int) -> np.ndarray:
    """4-connected component of m containing (sy, sx)."""
    from collections import deque
    out = np.zeros_like(m)
    if not m[sy, sx]:
        raise SystemExit("seed not on mask")
    q = deque([(sy, sx)])
    out[sy, sx] = True
    H, W = m.shape
    while q:
        y, x = q.popleft()
        for ny, nx in ((y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)):
            if 0 <= ny < H and 0 <= nx < W and m[ny, nx] and not out[ny, nx]:
                out[ny, nx] = True
                q.append((ny, nx))
    return out


def auto_line_box(old_mask, box, safe):
    """Cap box of the ORIGINAL line: top = first inked row, baseline = last row with >= 30% of the peak ink."""
    rows = old_mask.sum(1)
    ink = np.nonzero(rows >= 2)[0]
    heavy = np.nonzero(rows >= 0.3 * rows.max())[0]
    top, base = box[1] + ink.min(), box[1] + heavy.max() + 1
    return [safe[0], top, safe[2], base]


# ---------------------------------------------------------------- operations
def op_panel(el, color, opacity, rng, cover_log):
    """Painted legend on an opaque panel: remove old legend, draw the new one (mask untouched)."""
    rgb = color[..., :3]
    legend = LEGEND[el["legend"]](rgb.astype(int))
    hole = np.zeros(legend.shape, bool)
    for b in el.get("erase", []):
        sy, sx = box_slices(b)
        pix = rgb[sy, sx].astype(np.float64)
        strict = legend[sy, sx]
        near = dilate(strict, 2)
        lref = np.median(pix[strict], 0)
        bref = np.median(pix[~near], 0) if (~near).any() else 255 - lref
        dl = np.linalg.norm(pix - lref, axis=-1)
        db = np.linalg.norm(pix - bref, axis=-1)
        # anything that is not clean background near the legend is legend (incl. faint anti-aliasing)
        hole[sy, sx] |= ((dl < db * 1.25) | (db > el.get("bg_tol", 18))) & dilate(strict, 3)
    keep = np.zeros_like(hole)
    for b in el.get("keep", []):
        sy, sx = box_slices(b)
        keep[sy, sx] = True
    ebox = np.zeros_like(hole)
    for b in el.get("erase", []):
        ebox[box_slices(b)] = True
    hole = dilate(hole, el.get("erase_dilate", 1)) & ~keep & ebox
    ex = el["box"]
    sy, sx = box_slices(ex)
    hole_c = hole[sy, sx]
    flat = np.zeros_like(hole)
    for b in el.get("fill_boxes", []):  # areas repainted entirely (e.g. a coloured block removed)
        by, bx = box_slices(b)
        flat[by, bx] = True
    hole &= ~flat
    hole_c = hole[sy, sx]
    legend_sel = legend & ~dilate(~legend, 1)
    src_legend = rgb.copy()
    crop = rgb[sy, sx].copy()
    if hole_c.any():
        fill_src = crop.copy()
        if "bg_from" in el:  # sample background grain from a clean area
            by, bx = box_slices(el["bg_from"])
            bgpix = rgb[by, bx].reshape(-1, 3).astype(np.float64)
            fill = np.median(bgpix, 0)
            known = ~hole_c
            fill_src[hole_c] = fill
        new = inpaint(fill_src, hole_c, rng, iters=el.get("inpaint_iters", 300))
        crop = new.astype(np.uint8)
    flat_c = flat[sy, sx]
    if flat_c.any():
        by, bx = box_slices(el["bg_from"])
        bg = np.zeros(legend.shape, bool)
        bg[by, bx] = True
        crop[flat_c] = grain_color(rgb, bg, rng, flat_c.sum()).clip(0, 255).astype(np.uint8)
    # draw lines
    lsel = legend_sel.copy()
    if "legend_from" in el:
        by, bx = box_slices(el["legend_from"])
        m = np.zeros_like(lsel)
        m[by, bx] = lsel[by, bx]
        lsel = m
    else:
        m = np.zeros_like(lsel)
        for b in el.get("erase", []):
            by, bx = box_slices(b)
            m[by, bx] |= lsel[by, bx]
        lsel = m
    cov = np.zeros(legend.shape)
    for line in el.get("lines", []):
        spec = dict(el.get("style", {}))
        spec.update(line.get("style", {}))
        cov = np.maximum(cov, render_line(line["text"], spec, line["box"], spec.get("cap_ref", "H")))
    cov_c = cov[sy, sx]
    ink = cov_c > 0.02
    if ink.any():
        if "color" in el:
            lc = np.tile(np.array(el["color"], np.float64), (ink.sum(), 1))
        else:
            lc = grain_color(src_legend, lsel, rng, ink.sum())
        a = cov_c[ink][:, None]
        c = crop[ink].astype(np.float64)
        crop[ink] = (c * (1 - a) + lc * a).clip(0, 255).astype(np.uint8)
    color[sy, sx, :3] = crop
    cover_log.append(el["id"])


def op_glyph(el, color, opacity, rng, cover_log):
    """Glyph tile: the letter shape lives in the opacity map; rewrite mask + base colour of the tile."""
    sy, sx = box_slices(el["box"])
    old = opacity[sy, sx, 0] > 128
    rgb = color[..., :3]
    letter_sel = np.zeros(opacity.shape[:2], bool)
    letter_sel[sy, sx] = old
    cov = np.zeros(opacity.shape[:2])
    for line in el["lines"]:
        if line.get("box") == "auto" or "box" not in line:
            line["box"] = auto_line_box(old, el["box"], el.get("safe", el["box"]))
        spec = dict(el.get("style", {}))
        spec.update(line.get("style", {}))
        cov = np.maximum(cov, render_line(line["text"], spec, line["box"], spec.get("cap_ref", "H")))
    cov_c = cov[sy, sx]
    # opacity: clear the tile, write new letters (RGB channels, alpha untouched)
    newmask = (cov_c * 255).round().astype(np.uint8)
    for ch in range(3):
        opacity[sy, sx, ch] = newmask
    # base colour: letters painted with the original letter colour (+grain), bled 3 px so that
    # bilinear/mip filtering at the mask edge never picks the old background
    ink = dilate(cov_c > 0.02, 3)
    lc = grain_color(rgb, letter_sel, rng, ink.sum())
    crop = color[sy, sx, :3].copy()
    crop[ink] = lc.clip(0, 255).astype(np.uint8)
    color[sy, sx, :3] = crop
    cover_log.append(el["id"])


def op_r2(el, color, opacity, rng, cover_log):
    """US YIELD -> Brazilian R-2: white field, red border (orla), no legend. Outer triangle untouched."""
    x0, y0, x1, y1 = el["box"]
    rgb = color[..., :3].astype(int)
    red = LEGEND["red"](rgb)
    sub = connected(red[y0:y1, x0:x1], el["seed"][1] - y0, el["seed"][0] - x0)
    ys, xs = np.nonzero(sub)
    # robust outer triangle: fit the slanted edges on the straight part of each side, top edge by median
    rows = range(ys.min() + 14, ys.max() - 30)
    yl, xl, xr = [], [], []
    for yy in rows:
        r = np.nonzero(sub[yy])[0]
        if len(r):
            yl.append(yy); xl.append(r.min()); xr.append(r.max() + 1)
    al, bl = np.polyfit(yl, xl, 1)
    ar, br = np.polyfit(yl, xr, 1)
    mid = range(int(al * (ys.min() + 14) + bl) + 20, int(ar * (ys.min() + 14) + br) - 20)
    ytop = float(np.median([np.nonzero(sub[:, c])[0].min() for c in mid]))
    ybot = (br - bl) / (al - ar)
    tri = np.array([[al * ytop + bl, ytop], [ar * ytop + br, ytop], [al * ybot + bl, ybot]]) + [x0, y0]
    cen = tri.mean(0)
    border = el["orla_px"]
    # inner triangle: offset each edge inward by `border`
    def inset(p, q, r_, d):
        # line through p,q moved towards r_
        n = np.array([-(q - p)[1], (q - p)[0]], float)
        n /= np.linalg.norm(n)
        if np.dot(r_ - p, n) < 0:
            n = -n
        return p + n * d, q + n * d

    lines = [inset(tri[0], tri[1], tri[2], border), inset(tri[1], tri[2], tri[0], border), inset(tri[2], tri[0], tri[1], border)]

    def intersect(l1, l2):
        (p1, p2), (p3, p4) = l1, l2
        d1, d2 = p2 - p1, p4 - p3
        cr = lambda u, v: u[0] * v[1] - u[1] * v[0]
        t = cr(p3 - p1, d2) / cr(d1, d2)
        return p1 + t * d1

    inner = np.array([intersect(lines[2], lines[0]), intersect(lines[0], lines[1]), intersect(lines[1], lines[2])])
    # coverage of the inner triangle (supersampled) inside box
    W, H = (x1 - x0) * SS, (y1 - y0) * SS
    im = Image.new("L", (W, H), 0)
    ImageDraw.Draw(im).polygon([tuple((p - [x0, y0]) * SS) for p in inner], fill=255)
    cov = np.asarray(im.resize((x1 - x0, y1 - y0), Image.LANCZOS), np.float64) / 255.0
    # white field colour + grain from the existing white centre
    white = LEGEND["white"](rgb[y0:y1, x0:x1]) & (cov > 0.99)
    ink = cov > 0.01
    crop = color[y0:y1, x0:x1, :3].copy()
    wc = grain_color(color[y0:y1, x0:x1, :3], white, rng, ink.sum())
    a = cov[ink][:, None]
    crop[ink] = (crop[ink] * (1 - a) + wc * a).clip(0, 255).astype(np.uint8)
    color[y0:y1, x0:x1, :3] = crop
    el["_geometry"] = {"outer": tri.round(1).tolist(), "inner": inner.round(1).tolist()}
    cover_log.append(el["id"])


def op_r3(el, color, opacity, rng, cover_log):
    """DO NOT ENTER -> R-3: remove the white words, keep red disc, white bar and white rim."""
    rgb = color[..., :3]
    x0, y0, x1, y1 = el["box"]
    red = LEGEND["red"](rgb.astype(int))
    white = LEGEND["white"](rgb.astype(int))
    ys, xs = np.nonzero(red[y0:y1, x0:x1])
    cx, cy = x0 + (xs.min() + xs.max() + 1) / 2, y0 + (ys.min() + ys.max() + 1) / 2
    r_in = (xs.max() - xs.min() + 1) / 2 - el.get("rim_margin", 1)
    # white bar: white run through the centre
    icx, icy = int(round(cx)), int(round(cy))
    l = icx
    while white[icy, l - 1]:
        l -= 1
    r = icx
    while white[icy, r + 1]:
        r += 1
    t = icy
    while white[t - 1, icx]:
        t -= 1
    b = icy
    while white[b + 1, icx]:
        b += 1
    bx0, by0, bx1, by1 = l, t, r + 1, b + 1
    el["_geometry"] = {"center": [round(cx, 1), round(cy, 1)], "inner_radius": round(float(r_in), 1),
                       "bar": [int(bx0), int(by0), int(bx1), int(by1)]}
    yy, xx = np.mgrid[0:1024, 0:2048]
    disc = (xx - cx) ** 2 + (yy - cy) ** 2 <= r_in ** 2
    bar = (xx >= bx0) & (xx < bx1) & (yy >= by0) & (yy < by1)
    pix = rgb.astype(np.float64)
    wref = np.median(pix[white & disc & ~bar], 0)
    rref = np.median(pix[red & disc], 0)
    whitish = np.linalg.norm(pix - wref, axis=-1) < np.linalg.norm(pix - rref, axis=-1) * 1.4
    hole = dilate(whitish & disc & ~dilate(bar, 1), 1) & disc & ~dilate(bar, 1)
    crop = rgb[y0:y1, x0:x1].copy()
    h = hole[y0:y1, x0:x1]
    color[y0:y1, x0:x1, :3] = inpaint(crop, h, rng, iters=300).astype(np.uint8)
    cover_log.append(el["id"])


OPS = {"panel": op_panel, "glyph": op_glyph, "r2": op_r2, "r3": op_r3}


# ---------------------------------------------------------------- UV evidence
def uv_footprints():
    """Instanced West Coast meshes -> (instances, UV footprint mask on the atlas)."""
    import dae_uv
    usage = json.loads(MESH_USAGE.read_text(encoding="utf8"))
    out = {}
    for dae in sorted(MESH_DIR.rglob("*")):
        if dae.suffix.lower() != ".dae":
            continue
        inst = usage.get(dae.stem, {}).get("instances", 0)
        if inst == 0:
            continue
        mask, items = dae_uv.footprint([dae], "roadsigns", (2048, 1024))
        if items:
            out[dae.stem] = (inst, mask)
    return out


def evidence(box, foot):
    """Meshes whose UV footprint covers >= 40 % of the element box (the element is sampled by them)."""
    x0, y0, x1, y1 = box
    meshes, cover = {}, {}
    for mesh, (inst, mask) in foot.items():
        c = float(mask[y0:y1, x0:x1].mean())
        if c >= 0.4:  # a triangular sign (R-2) fills ~half of its bounding box
            meshes[mesh] = inst
            cover[mesh] = round(c, 3)
    return {"meshes": meshes, "uv_coverage": cover}


def cmd_regions(layout):
    foot = uv_footprints()
    out = {"_doc": "Generated by build_t_roadsigns.py regions: every edited element with the UV quads "
                   "(instanced West Coast meshes, material roadsigns) that sample it.", "elements": []}
    regions_color, regions_opacity = [], []
    for el in layout["elements"]:
        ev = evidence(el["box"], foot)
        if not ev["meshes"] and not el.get("uv_override"):
            raise SystemExit(f"{el['id']}: no instanced UV quad covers {el['box']} -> not an allowed region")
        rec = {"id": el["id"], "op": el["op"], "box": el["box"], **ev}
        out["elements"].append(rec)
        x0, y0, x1, y1 = el["box"]
        src = "UV quads of " + ", ".join(f"{m}.dae ({n} inst.)" for m, n in sorted(ev["meshes"].items())) + "; Phase 5"
        reg = {"id": el["id"], "x": x0, "y": y0, "width": x1 - x0, "height": y1 - y0, "source": src}
        regions_color.append(reg)
        if el["op"] == "glyph":
            regions_opacity.append(reg)
    REGIONS.write_text(json.dumps(out, indent=1) + "\n", encoding="utf8")
    allowed = json.loads(ALLOWED.read_text(encoding="utf8"))
    keep = [r for r in allowed["t_roadsigns_b.color"]["regions"] if r["id"] in
            ()]
    allowed["t_roadsigns_b.color"]["regions"] = keep + regions_color
    allowed["t_roadsigns_o.data"] = {"size": [2048, 1024], "regions": regions_opacity}
    ALLOWED.write_text(json.dumps(allowed, indent=2, ensure_ascii=False) + "\n", encoding="utf8")
    print(f"regions.json: {len(out['elements'])} elements; allowed_regions updated "
          f"({len(regions_color)} colour, {len(regions_opacity)} opacity)")


def cmd_build(layout):
    color, opacity = load_originals()
    rng = np.random.default_rng(20260930)
    done = []
    for el in layout["elements"]:
        OPS[el["op"]](el, color, opacity, rng, done)
    OUT_COLOR.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(color, "RGBA").save(OUT_COLOR, optimize=False)
    Image.fromarray(opacity, "RGBA").save(OUT_OPACITY, optimize=False)
    print(f"{len(done)} elements -> {OUT_COLOR.relative_to(REPO)}, {OUT_OPACITY.relative_to(REPO)}")
    geo = {el["id"]: el["_geometry"] for el in layout["elements"] if "_geometry" in el}
    if geo:
        print("geometry:", json.dumps(geo))


def cmd_preview(layout, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    a = Image.open(ORIG_COLOR).convert("RGBA")
    b = Image.open(OUT_COLOR).convert("RGBA")
    ao = Image.open(ORIG_OPACITY).convert("L")
    bo = Image.open(OUT_OPACITY).convert("L")
    tiles = []
    for el in layout["elements"]:
        x0, y0, x1, y1 = el["box"]
        m = 6
        bx = (max(x0 - m, 0), max(y0 - m, 0), min(x1 + m, 2048), min(y1 + m, 1024))
        pa, pb = a.crop(bx), b.crop(bx)
        if el["op"] == "glyph":  # show what the sign shows: colour where mask >= 128
            for im, mo in ((pa, ao), (pb, bo)):
                mm = mo.crop(bx).point(lambda v: 255 if v >= 128 else 0)
                bg = Image.new("RGBA", im.size, (30, 70, 50, 255))
                bg.paste(im, (0, 0), mm)
                im.paste(bg)
        s = 2
        w, h = pa.width * s, pa.height * s
        t = Image.new("RGB", (w * 2 + 6, h + 14), (0, 0, 0))
        t.paste(pa.resize((w, h), Image.LANCZOS).convert("RGB"), (0, 14))
        t.paste(pb.resize((w, h), Image.LANCZOS).convert("RGB"), (w + 6, 14))
        ImageDraw.Draw(t).text((2, 1), el["id"], fill=(255, 255, 0))
        t.save(out_dir / f"{el['id']}.png")
        tiles.append(t)
    print(f"{len(tiles)} previews -> {out_dir}")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["regions", "build", "preview"])
    ap.add_argument("--only", nargs="*", help="restrict to element ids (build/preview)")
    ap.add_argument("--out", default=str(REPO / "working/temporary/t_roadsigns_preview"))
    a = ap.parse_args(argv)
    layout = json.loads(LAYOUT.read_text(encoding="utf8"))
    if a.only:
        layout["elements"] = [e for e in layout["elements"] if e["id"] in a.only]
    if a.cmd == "regions":
        cmd_regions(layout)
    elif a.cmd == "build":
        cmd_build(layout)
    else:
        cmd_preview(layout, Path(a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
