"""Brazilian R-19 speed-limit signs (MBST Vol. I) for the West Coast `sign_speed*.dae` meshes.

One parameter set -> three outputs, so the vector master and the textures never drift:
    working/layered/r19/r19_<v>.svg              editable vector master (physical units, metres)
    working/png/r19/t_r19_<v>_b.color.png        base colour 512x1024 (maps the 0.7317 x 1.0 m panel)
    working/png/r19/t_r19_o.data.png             opacity (disc) shared by every value and by the back face

    python working/layered/r19/build_r19.py            # all values in VALUES
    python working/layered/r19/build_r19.py 10 40 60   # explicit values (future expansion)

The panel of sign_speed5/25.dae is 0.7317 m wide x 1.0 m tall; the disc is centred on it and the
corners are cut by the opacity map (alphaTest 128, like the original `roadsigns` material).
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
OUT = REPO / "working/png/r19"
FONT = "C:/Windows/Fonts/bahnschrift.ttf"   # system font (DIN 1451 design) ~ MBST Serie D/E(M) -> human_typography_review_required

VALUES = [10, 40]
PANEL_W, PANEL_H = 0.7317, 1.0          # metres, from sign_speed*.dae (x +-0.36584, z +-0.5)
TEX_W, TEX_H = 512, 1024                 # texture covers the whole panel (u: width, v: height)
SS = 4000                                # px per metre for the supersampled render
# MBST R-19: circular, white field, red border (orla), black numerals + "km/h", centred
D = 0.99 * PANEL_W                       # disc diameter (1 % margin keeps the edge off the texture border)
ORLA = 0.10 * D                          # red border width
NUM_H = 0.40 * D                         # numeral (cap) height
NUM_Y = -0.045 * D                       # numeral centre offset (up = negative), leaves room for km/h
UNIT_H = 0.085 * D                       # "k" ascender height
UNIT_Y = 0.255 * D                       # km/h baseline offset from centre (down)
COLORS = {"white": (236, 236, 232), "red": (196, 32, 40), "black": (22, 22, 22)}
NUM_STYLE = {"wght": 700, "wdth": 88}
UNIT_STYLE = {"wght": 600, "wdth": 100}


def _font(size, style):
    f = ImageFont.truetype(FONT, size)
    f.set_variation_by_axes([style["wght"], style["wdth"]])
    return f


def _fit_font(text, cap_px, style, ref="0"):
    probe = _font(400, style)
    b = probe.getbbox(ref)
    return _font(max(4, int(400 * cap_px / (b[3] - b[1]))), style)


def render(value: int) -> tuple[Image.Image, Image.Image]:
    W, H = int(round(PANEL_W * SS)), int(round(PANEL_H * SS))
    cx, cy = W / 2, H / 2
    r = D * SS / 2
    color = Image.new("RGB", (W, H), COLORS["red"])        # outside the disc = border colour (no halo)
    mask = Image.new("L", (W, H), 0)
    dc, dm = ImageDraw.Draw(color), ImageDraw.Draw(mask)
    dm.ellipse([cx - r, cy - r, cx + r, cy + r], fill=255)
    ri = r - ORLA * SS
    dc.ellipse([cx - ri, cy - ri, cx + ri, cy + ri], fill=COLORS["white"])
    # numerals
    f = _fit_font(str(value), NUM_H * SS, NUM_STYLE)
    b = f.getbbox(str(value))
    tx = cx - (b[0] + b[2]) / 2
    ty = cy + NUM_Y * SS - (b[1] + b[3]) / 2
    dc.text((tx, ty), str(value), font=f, fill=COLORS["black"])
    # km/h
    fu = _fit_font("km/h", UNIT_H * SS, UNIT_STYLE, ref="k")
    bu = fu.getbbox("km/h")
    kb = fu.getbbox("k")
    ux = cx - (bu[0] + bu[2]) / 2
    uy = cy + UNIT_Y * SS - kb[3]
    dc.text((ux, uy), "km/h", font=fu, fill=COLORS["black"])
    # subtle weathering: low-frequency luminance from the ORIGINAL white speed board of the atlas
    board = REPO / "source/originals/png/t_roadsigns_b.color.png"
    col = np.asarray(color, np.float64)
    if board.exists():
        patch = Image.open(board).convert("L").crop((380, 200, 506, 372)).resize((W, H), Image.BICUBIC)
        lum = np.asarray(patch, np.float64)
        col *= (1.0 + 0.6 * (lum - lum.mean()) / 255.0)[..., None]
    rng = np.random.default_rng(1900 + value)
    small = rng.normal(0, 2.2, (H // 8, W // 8))
    noise = np.asarray(Image.fromarray(small.astype(np.float32)).resize((W, H), Image.BICUBIC))
    col += noise[..., None]
    color = Image.fromarray(col.clip(0, 255).astype(np.uint8))
    color = color.resize((TEX_W, TEX_H), Image.LANCZOS).convert("RGBA")
    mask = mask.resize((TEX_W, TEX_H), Image.LANCZOS)
    return color, mask


def svg(value: int) -> str:
    """Vector master in metres (viewBox = panel), same parameters as render()."""
    cx, cy = PANEL_W / 2, PANEL_H / 2
    r, ri = D / 2, D / 2 - ORLA
    def c(k):
        return "#%02x%02x%02x" % COLORS[k]
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- R-19 {value} km/h - master for t_r19_{value}_b.color (generated by build_r19.py; edit the parameters there).
     Panel 0.7317 x 1.0 m (sign_speed*.dae). MBST Vol. I: circular, white field, red border, black numerals, km/h.
     Font: Bahnschrift (approximation of Serie D/E(M)) - human_typography_review_required. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{PANEL_W * 1000:.1f}mm" height="{PANEL_H * 1000:.1f}mm" viewBox="0 0 {PANEL_W} {PANEL_H}">
  <circle cx="{cx:.5f}" cy="{cy:.5f}" r="{r:.5f}" fill="{c('red')}"/>
  <circle cx="{cx:.5f}" cy="{cy:.5f}" r="{ri:.5f}" fill="{c('white')}"/>
  <text x="{cx:.5f}" y="{cy + NUM_Y + NUM_H / 2:.5f}" text-anchor="middle" font-family="Bahnschrift" font-weight="{NUM_STYLE['wght']}"
        font-stretch="{NUM_STYLE['wdth']}%" font-size="{NUM_H / 0.7:.5f}" fill="{c('black')}">{value}</text>
  <text x="{cx:.5f}" y="{cy + UNIT_Y:.5f}" text-anchor="middle" font-family="Bahnschrift" font-weight="{UNIT_STYLE['wght']}"
        font-size="{UNIT_H / 0.72:.5f}" fill="{c('black')}">km/h</text>
</svg>
"""


def main(argv=None) -> int:
    values = [int(v) for v in (argv or sys.argv[1:])] or VALUES
    OUT.mkdir(parents=True, exist_ok=True)
    mask_ref = None
    for v in values:
        if v % 10:
            raise SystemExit(f"{v}: R-19 values must be multiples of 10 (MBST-I p.35)")
        color, mask = render(v)
        color.save(OUT / f"t_r19_{v}_b.color.png")
        (HERE / f"r19_{v}.svg").write_text(svg(v), encoding="utf8")
        if mask_ref is None:
            mask_ref = mask
        print(f"R-19 {v}: {OUT.relative_to(REPO)}/t_r19_{v}_b.color.png + r19_{v}.svg")
    m = np.asarray(mask_ref)
    Image.fromarray(np.stack([m, m, m, np.full_like(m, 255)], -1), "RGBA").save(OUT / "t_r19_o.data.png")
    print(f"opacity: {OUT.relative_to(REPO)}/t_r19_o.data.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
